name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.18.x, 1.19.x, tip]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
      - run: go vet ./...
      - run: go test -short -timeout 1h ./...
      - run: go test -timeout 30m -race -run "TestDB_(Concurrent|GoleveldbIssue74)" ./leveldb
